name: Build Ebooks

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: pandoc/ubuntu:edge

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Made build.sh executable
      run: chmod +x build.sh
    - name: build the ebooks
      run: sh build.sh
    - name: Upload builds
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: build/
