name: Build Ebooks

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  container-job:
    runs-on: ubuntu-latest

    container:
      image: pandoc/latex

    steps:
    - uses: actions/checkout@v1
    - run: chmod +x build.sh
    - run: ./build.sh
